version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      jekyll-dependencies:
        patterns:
          - "jekyll*"
          - "kramdown*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

