# Site
name: 'Thoughts & Tricks'
description: 'Personal thoughts and some tricks discovered along the way'
tagline: Personal thoughts and some tricks discovered along the way

logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
# disqus: 'demowebsite'
# email: 'wowthemesnet@gmail.com'
# mailchimp-list: 'https://gmail.us20.list-manage.com/subscribe/post?u=3805f7049125d3cfaa7ef661a&amp;id=0364d23938'
google_analytics: G-F6G0HN1JDJ

include: ["_pages"]
permalink: posts/:title/

locale: en_US

twitter:
  card: summary

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - rouge
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
